// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaVLyDUlPNbjIm_89iXlpsrFsN424EdKs',
    appId: '1:369763108654:android:82265b6a0abcdfa544dcbf',
    messagingSenderId: '369763108654',
    projectId: 'fooddeliveryapp-7a68f',
    storageBucket: 'fooddeliveryapp-7a68f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFfufHlXd9KuQsSPJgn8lgON3d5UYG31o',
    appId: '1:369763108654:ios:fb3f914fa00b945944dcbf',
    messagingSenderId: '369763108654',
    projectId: 'fooddeliveryapp-7a68f',
    storageBucket: 'fooddeliveryapp-7a68f.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMCL1QRnJ4Gby9-z9otayDygDnkQogPBY',
    appId: '1:626137820503:web:a5fcf01483359876bc2212',
    messagingSenderId: '626137820503',
    projectId: 'quizapp-3b15c',
    authDomain: 'quizapp-3b15c.firebaseapp.com',
    storageBucket: 'quizapp-3b15c.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJxXoI2EJgKXmtohI7q0too-iFgS-9LRQ',
    appId: '1:626137820503:ios:aaf39b27d82a71fcbc2212',
    messagingSenderId: '626137820503',
    projectId: 'quizapp-3b15c',
    storageBucket: 'quizapp-3b15c.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMCL1QRnJ4Gby9-z9otayDygDnkQogPBY',
    appId: '1:626137820503:web:dcea73a34891ecb9bc2212',
    messagingSenderId: '626137820503',
    projectId: 'quizapp-3b15c',
    authDomain: 'quizapp-3b15c.firebaseapp.com',
    storageBucket: 'quizapp-3b15c.appspot.com',
  );

}